#!/bin/bash
# Minimal Sonarr setup - ONLY for Bazarr subtitle integration

echo "🎯 Setting up minimal Sonarr for Bazarr subtitle management"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  NOTE: This Sonarr is ONLY for library management."
echo "   You don't need to use it for downloads - it just tells"
echo "   Bazarr what TV shows/episodes you have."
echo ""

# Start Sonarr
echo "1️⃣  Starting Sonarr container..."
docker compose -f docker-compose-sonarr.yml up -d

if [ $? -eq 0 ]; then
    echo "   ✅ Sonarr started"
    echo ""
    sleep 3

    echo "2️⃣  Waiting for Sonarr to initialize (15 seconds)..."
    sleep 15

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ Sonarr is ready!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📝 QUICK SETUP (5 minutes):"
    echo ""
    echo "════════════════════════════════════════════════════════"
    echo "STEP 1: Configure Sonarr"
    echo "════════════════════════════════════════════════════════"
    echo "→ Open: http://localhost:8989"
    echo ""
    echo "First-time setup:"
    echo "  • Skip authentication (or set simple password)"
    echo "  • Click through welcome wizard"
    echo ""
    echo "Add Root Folder:"
    echo "  → Settings → Media Management → Root Folders"
    echo "  → Add: /tv"
    echo "  → Save"
    echo ""
    echo "Get API Key:"
    echo "  → Settings → General → Security"
    echo "  → Copy the API Key (you'll need this for Bazarr)"
    echo ""

    echo "════════════════════════════════════════════════════════"
    echo "STEP 2: Import Law & Order SVU"
    echo "════════════════════════════════════════════════════════"
    echo "→ Series → Import Existing Series"
    echo ""
    echo "  • Select root folder: /tv"
    echo "  • Find: Law and Order - SVU (1999 - ongoing)..."
    echo "  • Click the folder"
    echo "  • Monitor: All Episodes"
    echo "  • Quality: Any (doesn't matter, you already have files)"
    echo "  • Click 'Import'"
    echo ""
    echo "  Sonarr will scan and recognize all episodes!"
    echo ""

    echo "════════════════════════════════════════════════════════"
    echo "STEP 3: Connect Bazarr to Sonarr"
    echo "════════════════════════════════════════════════════════"
    echo "→ http://localhost:6767/settings/sonarr"
    echo ""
    echo "  • Enable Sonarr: Yes"
    echo "  • Address: sonarr (or localhost)"
    echo "  • Port: 8989"
    echo "  • API Key: [paste from Sonarr]"
    echo "  • Test → Save"
    echo ""

    echo "════════════════════════════════════════════════════════"
    echo "STEP 4: Add Series in Bazarr"
    echo "════════════════════════════════════════════════════════"
    echo "→ http://localhost:6767/series"
    echo ""
    echo "  NOW you'll see 'Add Series' button!"
    echo ""
    echo "  • Click 'Add Series'"
    echo "  • You'll see Law & Order SVU from Sonarr"
    echo "  • Select it"
    echo "  • Languages: English"
    echo "  • Enable subtitle sync: Yes"
    echo "  • Add"
    echo ""

    echo "════════════════════════════════════════════════════════"
    echo "STEP 5: Download Subtitles"
    echo "════════════════════════════════════════════════════════"
    echo "→ http://localhost:6767/series"
    echo ""
    echo "  • Click on Law & Order SVU"
    echo "  • Tools → Search All Episodes"
    echo "  • Wait 10-30 minutes for all subtitles"
    echo ""

    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "💡 TIP: You can disable/ignore Sonarr after this!"
    echo "   Once Bazarr knows about the series, it will keep"
    echo "   managing subtitles even if Sonarr is stopped."
    echo ""
else
    echo "   ❌ Failed to start Sonarr"
    echo "   Try: docker compose -f docker-compose-sonarr.yml up -d"
fi
