#!/bin/bash
# Configure Bazarr for manual series management with subtitle sync

BAZARR_URL="http://localhost:6767"
BAZARR_API_KEY="a5421902220f09abd682e7d30ed1cc20"

echo "🔧 Configuring Bazarr for Manual Mode + Subtitle Sync"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📝 REQUIRED SETTINGS (via Web UI):"
echo ""
echo "═══════════════════════════════════════════════════"
echo "1️⃣  ENABLE LANGUAGES"
echo "═══════════════════════════════════════════════════"
echo "→ http://localhost:6767/settings/languages"
echo ""
echo "  Languages Filter:"
echo "    • Click 'Add Language'"
echo "    • Select: English"
echo "    • Check ✓ Enabled"
echo "    • Click 'Save'"
echo ""

echo "═══════════════════════════════════════════════════"
echo "2️⃣  CONFIGURE SUBTITLE SYNC (THIS FIXES OUT-OF-SYNC!)"
echo "═══════════════════════════════════════════════════"
echo "→ http://localhost:6767/settings/subtitles"
echo ""
echo "  Subtitle Synchronization:"
echo "    • Enable ✓ 'Use embedded subtitles parser'"
echo "    • Enable ✓ 'Adaptive searching'"
echo "    • Enable ✓ 'Use scene name when available'"
echo ""
echo "  Anti-Captcha Options:"
echo "    • Enable ✓ 'Use Anti-Captcha for subtitles search'"
echo ""
echo "  Subtitle Naming:"
echo "    • Select: 'Movie or Episode file name'"
echo ""
echo "  Advanced Options (IMPORTANT FOR SYNC):"
echo "    • Enable ✓ 'Sync subtitles'"
echo "    • Sync threshold: 120 seconds (2 minutes)"
echo "    • Click 'Save'"
echo ""

echo "═══════════════════════════════════════════════════"
echo "3️⃣  ENABLE PROVIDERS"
echo "═══════════════════════════════════════════════════"
echo "→ http://localhost:6767/settings/providers"
echo ""
echo "  Best providers (no account needed):"
echo "    • ✓ TVsubtitles"
echo "    • ✓ Subscene"
echo ""
echo "  Best provider (free account):"
echo "    • ✓ OpenSubtitles.com"
echo "      - Sign up: https://www.opensubtitles.com/en/users/sign_up"
echo "      - Enter username/password in Bazarr"
echo ""

echo "═══════════════════════════════════════════════════"
echo "4️⃣  ADD LAW & ORDER SVU MANUALLY"
echo "═══════════════════════════════════════════════════"
echo "→ http://localhost:6767/series"
echo ""
echo "  Since Sonarr is disabled, use Manual Search:"
echo ""
echo "  • Click 'Add Series' button"
echo "  • Select 'Manual' tab (NOT Sonarr)"
echo "  • Click 'Add New Path'"
echo "  • Enter path: /tv"
echo "  • Browse to: Law and Order - SVU (1999 - ongoing) S01-S26 1080p WebDL H265 EAC3 2.0"
echo "  • Select the folder"
echo ""
echo "  Configure series:"
echo "    • Languages: English"
echo "    • Forced: No"
echo "    • HI: No (or Yes if you want hearing impaired subs)"
echo "    • Audio language: English"
echo ""
echo "  • Click 'Add'"
echo ""

echo "═══════════════════════════════════════════════════"
echo "5️⃣  TRIGGER SUBTITLE DOWNLOAD + SYNC"
echo "═══════════════════════════════════════════════════"
echo "→ http://localhost:6767/series"
echo ""
echo "  After adding the series:"
echo "    • Click on 'Law & Order SVU' in the list"
echo "    • Click 'Tools' dropdown"
echo "    • Select 'Search All Episodes'"
echo ""
echo "  Bazarr will:"
echo "    • Search all providers for each episode"
echo "    • Download the best matching subtitle"
echo "    • AUTOMATICALLY SYNC subtitles to match video timing"
echo "    • Save .srt files next to each .mp4 file"
echo ""

echo "═══════════════════════════════════════════════════"
echo "⚙️  OPTIONAL: SCHEDULED AUTO-SYNC"
echo "═══════════════════════════════════════════════════"
echo "→ http://localhost:6767/settings/scheduler"
echo ""
echo "  Set automatic searches:"
echo "    • Search and Download Subtitles: Every 6 hours"
echo "    • Sync Subtitles: Daily at 3:00 AM"
echo "    • Update Series from disk: Daily at 4:00 AM"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 KEY FEATURE: SUBTITLE SYNC"
echo ""
echo "When you enable 'Sync subtitles' in Settings → Subtitles:"
echo "  • Bazarr uses FFmpeg to analyze audio/video"
echo "  • Automatically adjusts subtitle timing"
echo "  • Fixes subs that are seconds or minutes off"
echo "  • Works even with downloaded subs from other sources"
echo ""
echo "This solves your out-of-sync problem! 🎯"
echo ""
